### ISSUE TITLE
generate fr and de - 3051

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/trident-2107#10]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@juliantap - Why is localization disabled for this repository?

**Comment by juliantap** [comment]
@ntap-bmegan, well that's interesting. My guess is that it was the first time I requested a new repo and I didn't select the languages!!!  😫 Apparently, no one noticed! Can we enable it now?

**Comment by ntap-bmegan** [comment]
That's unlikely to be how it happened, because you don't have to request localization now. It's enabled for the standard language set by default. You have to request an exemption. 

The `harmony_enabled: true` keyword is missing for prod. Add it in a hotfix after line 8, making sure that it's a sibling to `pdf_enabled` for `prod`. Do not add harmony for internal. 

![image](https://user-images.githubusercontent.com/56453501/202484851-0107b503-f470-45be-ab24-6e60aeaaec99.png)

Here's another repo you can compare: https://github.com/NetAppDocs/solidfire-active-iq/blob/main/project.yml

Also, why is `platform` empty? It should either not exist or - if you need the Cloud breadcrumb, be set for that. There's no reason for what's there now.

**Comment by juliantap** [comment]
@ntap-bmegan I went back to look and realized this was created before my time (by Amitha), so I don't know what was in the ticket. Anyway, I'll add `harmony_enabled` line. It's already in all the repos after 21.07. Do I have to do anything after I add this or will it automatically generate the translations?

I'll also remove the empty `platform`.

**Comment by ntap-bmegan** [comment]
Just make the change (dev and prod) and push it as you would any other change. Comment here when you push to public main and we'll take it from there.

**Comment by juliantap** [comment]
The changes are merged to internal & public. Thanks!

**Comment by ntap-bmegan** [comment]
FYI @netapp-gudugunti - We'll need to process all six languages, not just the two. :)

**Comment by ntap-bmegan** [comment]
Also FYI @netapp-gudugunti - I can get the size in a day or so when the reports are updated. When you finish your stuff, re-assign the issue to me.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - I've added the size. Should be ready to close when you finish your stuff.

**Comment by netapp-gudugunti** [comment]
Site is up and running.
Completed configs for six languages.
Total TOT: 30 minutes.
